Write a python program using Numpy to perform the following tasks

• Create a 1-D array and display the data type of the array.

• Create two 2D-arrays of the same shape and perform arithmetic operation on their
elements.

• Concatenate the above 2D-arrays along rows or columns and display the result.

• Convert the concatenated array into a 1D-Array and display it.

• Create a 3x3 identity matrix and print its shape, number of dimensions and datatype. 


In [4]:
import numpy as np

In [5]:
# 1. Create a 1-D array and display its data type
arr1D = np.array([10, 20, 30, 40, 50])
print("1-D Array:", arr1D)
print("Data type:", arr1D.dtype)

1-D Array: [10 20 30 40 50]
Data type: int32


In [6]:
# 2. Create two 2D arrays and perform arithmetic operations
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("\n2D Array A:\n", a)
print("2D Array B:\n", b)
print("Addition:\n", a + b)
print("Subtraction:\n", a - b)
print("Multiplication:\n", a * b)
print("Division:\n", a / b)



2D Array A:
 [[1 2]
 [3 4]]
2D Array B:
 [[5 6]
 [7 8]]
Addition:
 [[ 6  8]
 [10 12]]
Subtraction:
 [[-4 -4]
 [-4 -4]]
Multiplication:
 [[ 5 12]
 [21 32]]
Division:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [7]:
# 3. Concatenate the 2D arrays along rows and display result
concat_rows = np.concatenate((a, b), axis=0)
print("\nConcatenated along rows:\n", concat_rows)


Concatenated along rows:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [8]:
# 4. Convert the concatenated array into 1D and display it
flattened = concat_rows.flatten()
print("\nFlattened 1D Array:\n", flattened)


Flattened 1D Array:
 [1 2 3 4 5 6 7 8]


In [9]:

# 5. Create 3x3 identity matrix and display shape, dimensions, datatype
identity = np.identity(3)
print("\n3x3 Identity Matrix:\n", identity)
print("Shape:", identity.shape)
print("Dimensions:", identity.ndim)
print("Data type:", identity.dtype)


3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Shape: (3, 3)
Dimensions: 2
Data type: float64


Write a python program using Numpy to perform the following tasks

• Create a 2x4 array of zeros and 4x2 array of ones and display it.

• For each of the above arrays , print their shape, number of dimensions and datatype.

• Convert 4x2 array of ones into 1D- Array and display the result.

• Reshape it into a different valid shape.

• Create a 4D-Array and convert its element to float.

In [10]:
import numpy as np
# 1. Create arrays of zeros and ones
zeros_arr = np.zeros((2, 4))
ones_arr = np.ones((4, 2))
print("2x4 Array of Zeros:\n", zeros_arr)
print("\n4x2 Array of Ones:\n", ones_arr)

2x4 Array of Zeros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

4x2 Array of Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [11]:
# 2. Print shape, dimensions, and datatype
print("\nShape of zeros_arr:", zeros_arr.shape)
print("Dimensions:", zeros_arr.ndim)
print("Data type:", zeros_arr.dtype)

print("\nShape of ones_arr:", ones_arr.shape)
print("Dimensions:", ones_arr.ndim)
print("Data type:", ones_arr.dtype)



Shape of zeros_arr: (2, 4)
Dimensions: 2
Data type: float64

Shape of ones_arr: (4, 2)
Dimensions: 2
Data type: float64


In [12]:
# 3. Convert 4x2 array of ones to 1D array
ones_flat = ones_arr.flatten()
print("\nFlattened 1D Array from ones_arr:\n", ones_flat)



Flattened 1D Array from ones_arr:
 [1. 1. 1. 1. 1. 1. 1. 1.]


In [13]:
# 4. Reshape it to a different valid shape (e.g., 2x4)
reshaped = ones_flat.reshape((2, 4))
print("\nReshaped to 2x4:\n", reshaped)



Reshaped to 2x4:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [14]:
# 5. Create a 4D array and convert its elements to float
arr_4D = np.array([[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]])
arr_4D_float = arr_4D.astype(float)
print("\n4D Array with float type:\n", arr_4D_float)
print("Shape:", arr_4D_float.shape)
print("Dimensions:", arr_4D_float.ndim)
print("Data type:", arr_4D_float.dtype)


4D Array with float type:
 [[[[1. 2.]
   [3. 4.]]

  [[5. 6.]
   [7. 8.]]]]
Shape: (1, 2, 2, 2)
Dimensions: 4
Data type: float64
